# 2Dpose exercises
* 1.a) find $\overset{\rightharpoonup}{p} = \begin{bmatrix} x\\ y \end{bmatrix}$ from the diagram on exercise pdf.

In [1]:
import numpy as np

In [2]:
Op1 = np.array([[1],[3]])
Op2 = np.array([[4],[2]])
Ap1 = np.array([[0],[2]])
Ap2 = np.array([[3],[1]])
Bp1 = np.array([[0],[-1]])
Bp2 = np.array([[2],[0]])
Cp1 = np.array([[3],[-2]])
Cp2 = np.array([[0],[-1]])

* 1.b) find the rotation matrix 
$^{from}T_{to} = \begin{bmatrix} 
cos\theta & -sin\theta\\
sin\theta & cos\theta
\end{bmatrix}$

In [3]:
def transMat(theta):
    T = np.array([[np.cos(theta), -np.sin(theta)],[np.sin(theta), np.cos(theta)]])
    return T

In [4]:
thetA = 0
OTA = transMat(thetA)
OTA

array([[ 1., -0.],
       [ 0.,  1.]])

In [5]:
thetB = -np.pi/4
OTB = transMat(thetB)
OTB

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

In [6]:
thetC = np.pi
OTC = transMat(thetC)
OTC

array([[-1.0000000e+00, -1.2246468e-16],
       [ 1.2246468e-16, -1.0000000e+00]])

* 1.c)

In [7]:
BthetaC = -(3*np.pi)/4
BTC = transMat(BthetaC)
BTC

array([[-0.70710678,  0.70710678],
       [-0.70710678, -0.70710678]])

In [8]:
CthetaA = np.pi
CTA = transMat(CthetaA)
CTA

array([[-1.0000000e+00, -1.2246468e-16],
       [ 1.2246468e-16, -1.0000000e+00]])

In [9]:
AthetaB = -np.pi/4
ATB = transMat(AthetaB)
ATB

array([[ 0.70710678,  0.70710678],
       [-0.70710678,  0.70710678]])

* 1.d) Use the obtained transform matrices to determin the position vectors

$$^{A}\overset{\sim}{p} = ^{B}T_A ^{B}\overset{\sim}{p} = (^{A}T_B)^{-1} \text{ } ^{B}\overset{\sim}{p} $$

OTA = np.append(OTA,np.array([[0,0]]), axis=0) #adds an extra row with zeros
Op = np.append(Op1,np.array([[1]]), axis=0) #adds a row with 1
OtA = np.array([[1],[1],[1]]) #Vector describing distance from O to A
OTA = np.append(OTA,OtA,axis=1) #Extends OTA matrix with AtO vector
OTAinv = np.linalg.inv(OTA) #inverts tha OTA matrix
Ap = np.delete(OTAinv.dot(Op),2,axis=0) #Removes the last row in this 3x1 matrix
Ap

In [11]:
'''
realizing that I am going to do this many times 
I made functions to do it for me
'''
def exTransMat(mat,vector):
    #defining variables
    row = 0
    coloumn = 1
    zeroRow = np.array([[0,0]])
    Mat = np.append(mat,zeroRow,axis=row)
    exMat = np.append(Mat,vector,axis=coloumn)
    return exMat

def exVector(vec):
    row = 0
    return np.append(vec,np.array([[1]]), axis=row)

In [12]:
OtB = np.array([[2],[4]]) #2D-vector from origin to B
OtBex = exVector(OtB)                
OTBex = exTransMat(OTB,OtBex)
OTBinv = np.linalg.inv(OTBex)
Bp = np.delete(OTBinv.dot(Op),2,axis=0)
Bp

array([[ 0.        ],
       [-1.41421356]])

In [13]:
OtC = np.array([[4],[1]]) #2D-vector from origin to C
OtCex = exVector(OtC)
OTCex = exTransMat(OTC,OtCex)
OTCinv = np.linalg.inv(OTCex)
Cp = np.delete(OTCinv.dot(Op),2,axis=0)
Cp

array([[ 3.],
       [-2.]])

In [14]:
Op2ex = exVector(Op2)
Ap_2 = np.delete(OTAinv.dot(Op2ex),2,axis=0)
Ap_2

array([[3.],
       [1.]])

In [15]:
Bp_2 = np.delete(OTBinv.dot(Op2ex),2,axis=0)
Bp_2 #e^-16 = 0

array([[ 2.82842712e+00],
       [-8.88178420e-16]])

In [16]:
Cp_2 = np.delete(OTCinv.dot(Op2ex),2,axis=0)
Cp_2 #e^-16 = 0

array([[ 4.4408921e-16],
       [-1.0000000e+00]])

* 2 Determine if a matrix is a valid rotation matrix

$det(R) = 1$ and $R^TR = I$

In [55]:
def validRot(R):
    detR = np.linalg.det(R)
    rtr = np.linalg.inv(R).dot(R)
    if (round(detR) == round(sum(rtr[0])) == round(sum(rtr[1])) == 1):
        print("This is a valid rotation matrix se for your self!")
        print(f"det(R) = {detR} I rounded it up to be {round(detR)}")
        print(f"Matrix = \n{rtr}\nI rounded first row to be {round(sum(rtr[0]))}\nand second {round(sum(rtr[0]))}")
    else:
        print("This matrix is not a valid rotation matrix")

In [49]:
R = np.array([[0.995, -0.0998],[0.0998, 0.995]])
validRot(R)

This is a valid rotation matrix se for your self!
det(R) = 0.9999850399999999 I rounded it up to be 1
Matrix = 
[[ 1.00000000e+00 -2.24732008e-18]
 [ 1.79944683e-18  1.00000000e+00]]
I rounded first row to be 1
and second 1


In [50]:
R = np.array([[1,0],[0,1]])
validRot(R)

This is a valid rotation matrix se for your self!
det(R) = 1.0 I rounded it up to be 1
Matrix = 
[[1. 0.]
 [0. 1.]]
I rounded first row to be 1
and second 1


In [54]:
R = np.array([[1,0],[0,-1]])
validRot(R)

Matrix: {R} is not a valid rotation matrix


In [56]:
R = np.array([[1,1],[0,2]])
validRot(R)

This matrix is not a valid rotation matrix


In [57]:
R = np.array([[np.sqrt(2)/2,-np.sqrt(2)/2],[np.sqrt(2)/2,np.sqrt(2)/2]])
validRot(R)

This is a valid rotation matrix se for your self!
det(R) = 1.0 I rounded it up to be 1
Matrix = 
[[ 1.00000000e+00 -1.01465364e-17]
 [-1.01465364e-17  1.00000000e+00]]
I rounded first row to be 1
and second 1


In [58]:
R = np.array([[-0.5,-0.866],[0.866,-0.5]])
validRot(R)

This is a valid rotation matrix se for your self!
det(R) = 0.999956 I rounded it up to be 1
Matrix = 
[[1.00000000e+00 5.55111512e-17]
 [2.64234839e-17 1.00000000e+00]]
I rounded first row to be 1
and second 1


In [59]:
R = np.array([[-0.5,-0.866],[0.866,0.5]])
validRot(R)

This matrix is not a valid rotation matrix


## Consider the rotation matrix 
$R(\theta) = \begin{bmatrix} 
cos(\theta) &  -sin(\theta)\\
sin(\theta) & cos(\theta) \end{bmatrix}$

* 3.a) Show that $R(0) = I_2$

$R(0) = \begin{bmatrix} 
cos(0) &  -sin(0)\\
sin(0) & cos(0) \end{bmatrix} =
\begin{bmatrix} 
1 &  0\\
0 & 1 \end{bmatrix} = I_2$

* 3.b) Show that for any angle $\theta$ $det(R(\theta)) = +1$

If $A = \begin{bmatrix}a & b\\ c & d \end{bmatrix}$
then $det(A) = \begin{vmatrix}a & b\\ c & d  \end{vmatrix} = ad - bc $

And we know from trigonometry that $cos^2 + sin^2 = 1$

Therfore $det(R) = \begin{vmatrix}cos(\theta) & -sin(\theta)\\ sin(\theta) & cos(\theta)  \end{vmatrix} 
= cos^2(\theta) + sin^2(\theta) = 1 $

* 3.c) Show that $R^TR = I_2$

$R^T = \begin{bmatrix} cos(\theta) & sin(\theta)\\-sin(\theta) & cos(\theta)\end{bmatrix}$

$R^TR = \begin{bmatrix} cos(\theta) & sin(\theta)\\-sin(\theta) & cos(\theta)\end{bmatrix}
\begin{bmatrix} cos(\theta) & -sin(\theta)\\sin(\theta) & cos(\theta)\end{bmatrix} = 
\begin{bmatrix} cos^2(\theta) + sin^2(\theta) & -cos(\theta)sin(\theta) + cos(\theta)sin(\theta) \\ -cos(\theta)sin(\theta) + cos(\theta)sin(\theta) & sin^2(\theta)+cos^2(\theta)\end{bmatrix} = \begin{bmatrix} 1 & 0\\ 0 & 1\end{bmatrix} = I_2$

* 3.d) Show that $R(-\theta) = R(\theta)^T$